version: '2.4'

networks:
  # Required for the devcontainer
  sindit_network:
    name: sindit_network

services:
  sindit_influx_db:
    image: influxdb:2.2
    hostname: sindit-influx-db
    container_name: sindit_influx_db
    restart: unless-stopped
    mem_limit: 4G

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=sindit_influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=sindit_influxdb
      - DOCKER_INFLUXDB_INIT_ORG=sindit
      - DOCKER_INFLUXDB_INIT_BUCKET=sindit
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sindit_influxdb_admin_token
    networks:
      - sindit_network
    volumes:
      - ./docker_mounted_storage/sindit_influx_db/data:/var/lib/influxdb2
      - ./docker_mounted_storage/sindit_influx_db/config:/etc/influxdb2
    healthcheck:
      test: "influx ping"
      interval: 5s
      timeout: 30s
      retries: 5

  sindit_neo4j_kg:
    image: neo4j:4.4-community
    hostname: sindit-neo4j-kg
    container_name: sindit_neo4j_kg
    mem_limit: 6G
    restart: unless-stopped

    volumes:
      - ./docker_mounted_storage/sindit_neo4j_kg/conf:/var/lib/neo4j/conf/
      - ./docker_mounted_storage/sindit_neo4j_kg/logs:/logs
      - ./docker_mounted_storage/sindit_neo4j_kg/data:/data
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - sindit_network
    environment:
      - NEO4J_AUTH=none
      # Neo4J plugins for metamodel, similarity analysis, RDF semantics, ...
      - NEO4JLABS_PLUGINS=["apoc", "n10s", "graph-data-science", "streams"]
      # Allow the separate endpoint "/rdf" for RDF mappings
      - NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf

  sindit_minio_s3:
    image: minio/minio
    hostname: sindit-minio-s3
    container_name: sindit_minio_s3
    mem_limit: 4G
    restart: unless-stopped
    volumes:
      - ./docker_mounted_storage/sindit_minio_s3_data:/data
    networks:
      - sindit_network
    environment:
      MINIO_ACCESS_KEY: sindit_minio_access_key
      MINIO_SECRET_KEY: sindit_minio_secret_key

      MINIO_ROOT_USER: sindit_minio
      MINIO_ROOT_PASSWORD: sindit_minio
    command: server --address 0.0.0.0:9000 --console-address ":9099" /data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
